<?php
$translate = $this->plugin('translate');
?>
<?php if ($prevPage || $nextPage): ?>
<div class="site-page-pagination">
    <?php echo $prevPage ? $this->hyperlink($translate($prevPage->title()), $prevPage->siteUrl(), ['class' => 'site-pagination-prev btn btn-primary']) : ''; ?>
    <?php echo $nextPage ? $this->hyperlink($translate($nextPage->title()), $nextPage->siteUrl(), ['class' => 'site-pagination-next btn btn-primary']) : ''; ?>
</div>
<?php endif; ?>