<?php
$translate = $this->plugin('translate');
$escape = $this->plugin('escapeHtml');
$this->headLink()->appendStylesheet($this->assetUrl('css/resource-page-blocks.css', 'Omeka'));
$this->htmlElement('body')->appendAttribute('class', 'item resource show');
$embedMedia = $this->siteSetting('item_media_embed', false);
$itemMedia = $item->media();
$nav = $site->publicNav();
$filterLocale = (bool) $this->siteSetting('filter_locale_values');
$lang = $this->lang();
$valueLang = $filterLocale ? [$lang, ''] : null;
$site_layout = $this->themeSetting('site_layout') !== null ? $this->themeSetting('site_layout') : 'default';

if ($this->themeSetting('theme_og_image') && $this->themeSetting('theme_og_image_include') == 1) {
    $this->headMeta()->appendProperty('og:image', $this->themeSettingAssetUrl('theme_og_image'));
    if ($this->themeSettingAsset('theme_og_image')->altText()) {
        $this->headMeta()->appendProperty('og:image:alt', $this->themeSettingAsset('theme_og_image')->altText());
    }
}

if ($site_layout == 'speakout') {
    //build media contents
    $thismedia = array('transcript' => null, 'audio' => null, 'pdf' => null);
    if ($embedMedia && $itemMedia) {
        foreach ($itemMedia as $media) {
            $thismediatype = $media->value('dcterms:type');
            if ($thismediatype == 'viewable_transcript') {
                $thismedia['transcript'] = $media->render();
            }
            elseif ($thismediatype == 'audio') {
                $thismedia['audio'][$media->title()] = $media->render();
            }
            elseif ($thismediatype == 'pdf_transcript') {
                $thismedia['pdf'] = $media->originalUrl();
            }
        }
    }
    // class for audio column
    $audioClass = !$thismedia['transcript'] ? 'no-transcript' : 'third';
}
?>
<nav class="breadcrumbs">
    <a href="<?php echo $site->siteUrl(); ?>"><?php echo $site->title(); ?></a> >
    <?php foreach ($item->sitePages($site->id()) as $sitePage): ?>
        <?php if ($sitePage->title() != $site->title()): ?>
            <?php echo $sitePage->link($sitePage->title()); ?> >
        <?php endif; ?>
    <?php endforeach; ?>
    <?php echo $item->displayTitle(null, $valueLang); ?>
</nav>
<?php echo $this->pageTitle($item->displayTitle(null, $valueLang), 2); ?>
<?php $this->trigger('view.show.before'); ?>
<?php if ($site_layout == 'speakout'): ?>
    <div class="speakout-item-layout">
        <div>
            <div id="itemproperties" class="<?php echo $audioClass; ?>">
                <?php if ($thismedia['audio']):
                foreach ($thismedia['audio'] as $audioTitle => $audio):
                    if (count($thismedia['audio']) > 1):
                    echo $audioTitle;
                    endif;
                    echo $audio;
                endforeach;
                endif;?>
                <div id="properties">
                    <div class="property">
                        <?php echo $item->displayValues(); ?>
                    </div>
                </div>
                <?php if ($thismedia['pdf'] && !$thismedia['transcript']):?>
                    <div>
                        <div id="transcriptinfo" class="full">
                            <a href="<?php echo $thismedia['pdf'];?>" target="_blank"><button>download PDF of transcript</button></a>
                        </div>
                    </div>
                <?php endif; ?>
            </div>
        </div>
        <?php if ($thismedia['transcript']): ?>
        <div id="itemtranscript" class="twothirds">
            <?php if ($thismedia['pdf']):?>
                <div>
                    <div id="transcriptinfo" class="full">
                        <h3>Transcript</h3>
                        <a href="<?php echo $thismedia['pdf'];?>" target="_blank"><button>download PDF</button></a>
                    </div>
                </div>
            <?php endif; ?>
            <div>
                <div class="full">
                    <?php echo $thismedia['transcript'];?>
                </div>
            </div>
        </div>
        <?php endif; ?>
    </div>
<?php else: ?>
    <?php if ($embedMedia && $itemMedia): ?>
        <div class="media-embeds">
        <?php foreach ($itemMedia as $media):
            echo $media->render();
        endforeach;
        ?>
        </div>
    <?php endif; ?>
    <?php echo $item->displayValues(); ?>
    <div class="property">
        <?php $itemSets = $item->itemSets(); ?>
        <?php if (count($itemSets) > 0): ?>
        <h3><?php echo $translate('Item sets'); ?></h3>
        <?php foreach ($itemSets as $itemSet): ?>
        <div class="value"><a href="<?php echo $escape($itemSet->url()); ?>"><?php echo $itemSet->displayTitle(null, ($filterLocale ? $lang : null)); ?></a></div>
        <?php endforeach; ?>
        <?php endif; ?>
    </div>
    <?php if (($this->siteSetting('show_attached_pages', true)) && ($sitePages = $item->sitePages($site->id()))): ?>
    <div class="property">
        <h3><?php echo $translate('Site pages'); ?></h3>
        <div class="values">
            <?php foreach ($sitePages as $sitePage): ?>
            <div class="value"><?php echo $sitePage->link($sitePage->title()); ?></div>
            <?php endforeach; ?>
        </div>
    </div>
    <?php endif; ?>
    <?php if (!$embedMedia && $itemMedia): ?>
    <div class="media-list">
        <?php foreach ($itemMedia as $media): ?>
            <?php echo $media->linkPretty(); ?>
        <?php endforeach; ?>
    </div>
    <?php endif; ?>
<?php endif; ?>
<?php
$page = $this->params()->fromQuery('page', 1);
$property = $this->params()->fromQuery('property');
$subjectValues = $item->displaySubjectValues([
    'page' => $page, 
    'perPage' => 25, 
    'resourceProperty' => $property
]);
?>
<?php if ($subjectValues): ?>
<div id="item-linked">
    <h3><?php echo $translate('Linked resources'); ?></h3>
    <?php echo $subjectValues; ?>
</div>
<?php endif; ?>

<?php $this->trigger('view.show.after'); ?>
