<?php
$this->headLink()->appendStylesheet($this->assetUrl('css/page-blocks.css', 'Omeka'));
$this->htmlElement('body')->appendAttribute('class', $pageBodyClass);
$this->pageTitle($page->title(), 2);
$nav = $site->publicNav();
$activePage = $nav->findActive($nav->getContainer());
switch ($this->siteSetting('subnav_display')) {
    case 'show';
        $displaySubnav = $this->displayNavigation;
        break;
    case 'hide':
        $displaySubnav = false;
        break;
    default:
        $displaySubnav = $displaySubnav = $this->displayNavigation && $activePage && $activePage['page']->hasPages();
}
$showPagePagination = $this->siteSetting('show_page_pagination', true);

if ($this->themeSetting('theme_og_image') && $this->themeSetting('theme_og_image_include') == 1) {
  $this->headMeta()->appendProperty('og:image', $this->themeSettingAssetUrl('theme_og_image'));
  if ($this->themeSettingAsset('theme_og_image')->altText()) {
    $this->headMeta()->appendProperty('og:image:alt', $this->themeSettingAsset('theme_og_image')->altText());
  }
}
?>

<?php if ($activePage): ?>
<?php if ($activePage['depth'] !== 0): ?>
<nav class="breadcrumbs"><?php echo $nav->breadcrumbs(); ?></nav>
<?php endif; ?>
<?php endif; ?>

<?php if ($activePage): ?>
    <?php if ($displaySubnav): ?>
      <button class="dcl-sub-menu-control" aria-controls="dcl-sub-menu-content" aria-expanded="false" role="button">Read More</button>
      <nav class="sub-menu" id="dcl-sub-menu-content"><?php echo $nav->menu()->renderSubMenu(); ?></nav>
    <?php endif; ?>
<?php endif; ?>

<?php $this->trigger('view.show.before'); ?>
<div class="blocks">
    <?php echo $this->content; ?>
</div>
<?php $this->trigger('view.show.after'); ?>
<?php if ($showPagePagination): ?>
<?php echo $this->sitePagePagination(); ?>
<?php endif; ?>
