<!-- override for alt text -->
<?php
$hyperlink = $this->plugin('hyperlink');
array_push($classes, $this->alignmentClass, $this->thumbnailType, 'file');
?>
<div class="<?php echo $this->escapeHtml(implode(' ', $classes)); ?>">
    <?php foreach ($attachments as $attachment): ?>
        <?php 
            $item = $attachment->item(); 
            if ($this->status()->isSiteRequest()) {
                $filterLocale = $this->siteSetting('filter_locale_values');
                $lang = $this->lang();
            } else {
                $filterLocale = false;
                $lang = null;
            }
        ?>
    <div class="item resource">
        <?php
        $media = $attachment->media() ?: $item->primaryMedia();
        if ($media):
            if ($mediaDisplay === 'thumbnail') {
                switch ($link) {
                    case 'original':
                        $url = $media->originalUrl();
                        break;
                    case 'item':
                        $url = $item->url();
                        break;
                    case 'media':
                        $url = $media->url();
                        break;
                    default:
                        throw new \InvalidArgumentException(sprintf('Invalid link type "%s"', $linkType));
                }
                $alttext = $media->altTextResolved();
                echo $hyperlink->raw($this->thumbnail($media, $thumbnailType, ['alt' => $alttext]), $url, ['title' => $item->displayTitle(null, ($filterLocale ? $lang : null))]);
            } else {
                echo $media->render([
                    'thumbnailType' => $thumbnailType,
                    'link' => $link,
                    'alt' => $media->altTextResolved(),
                ]);
            }
        endif;
        ?>
        <?php if ($showTitleOption === 'item_title'): ?>
        <h3><?php echo $item->link($item->displayTitle(null, ($filterLocale ? $lang : null))); ?></h3>
        <?php elseif ($showTitleOption === 'file_name'): ?>
        <h3><?php echo $media->displayTitle(null, ($filterLocale ? $lang : null)); ?></h3>
        <?php endif; ?>
        <?php $caption = $attachment->caption(); ?>
        <?php if ($caption): ?>
        <div class="caption"><?php echo $caption; ?></div>
        <?php endif; ?>
    </div>
    <?php endforeach; ?>
</div>
