<?php
$escape = $this->plugin('escapeHtml');
$siteTitle = $site->title();
$this->htmlElement('html')->setAttribute('lang', $this->lang());
$this->headMeta()->setCharset('utf-8');
$this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1');
$this->headTitle($siteTitle)->setSeparator(' · ');
$this->headLink([
    'rel' => 'manifest',
    'href' => $this->assetUrl('favicon_misc/site.webmanifest')
], 'PREPEND');
$this->headLink([
    'rel' => 'mask-icon',
    'color' => '#5bbad5',
    'href' => $this->assetUrl('img/safari-pinned-tab.svg')
], 'PREPEND');
$this->headMeta()->appendName('msapplication-TileColor', 'color="#da532c"');
$this->headMeta()->appendName('theme-color', 'color="#fff"');
$this->headLink([
    'rel' => 'apple-touch-icon', 
    'type' => 'image/png',
    'sizes' => '180x180',
    'href' => $this->assetUrl('img/apple-touch-icon.png')
], 'PREPEND');
$this->headLink([
    'rel' => 'shortcut icon', 
    'type' => 'image/png',
    'sizes' => '32x32',
    'href' => $this->assetUrl('img/favicon-32x32.png')
], 'PREPEND');
$this->headLink([
    'rel' => 'shortcut icon', 
    'type' => 'image/png',
    'sizes' => '16x16',
    'href' => $this->assetUrl('img/favicon-16x16.png')
], 'PREPEND');
$this->headTitle()->append($this->setting('installation_title', 'Omeka S'));
$this->headLink()->prependStylesheet($this->assetUrl('css/iconfonts.css', 'Omeka'));
$this->headLink()->prependStylesheet($this->assetUrl('font-awesome/css/font-awesome.min.css'));
$this->headLink()->prependStylesheet('https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200');
$this->headLink()->appendStylesheet($this->assetUrl('../node_modules/@accessible360/accessible-slick/slick/accessible-slick-theme.min.css'));
$this->headLink()->appendStylesheet($this->assetUrl('../node_modules/@accessible360/accessible-slick/slick/slick.min.css'));
$this->headScript()->appendFile($this->assetUrl('../node_modules/@accessible360/accessible-slick/slick/slick.min.js'));
$this->headLink()->appendStylesheet($this->assetUrl('../node_modules/@midzer/tobii/dist/tobii.min.css'));
$this->headScript()->appendFile($this->assetUrl('../node_modules/@midzer/tobii/dist/tobii.min.js'));
$this->headLink()->appendStylesheet($this->assetUrl('base_styles/omeka.min.css'));
$this->headLink()->appendStylesheet($this->assetUrl('css/style.css'));
$this->headScript()->appendFile('https://cdnjs.cloudflare.com/ajax/libs/uuid/8.1.0/uuidv4.min.js');
$this->headScript()->prependFile($this->assetUrl('js/default.js'));
$this->headScript()->prependFile($this->assetUrl('js/fontsession.js'));
$this->headScript()->prependFile($this->assetUrl('js/fontfaceobserver.js'));
$this->headScript()->prependFile($this->assetUrl('js/autolink.js'));
$this->headScript()->prependFile($this->assetUrl('js/global.js', 'Omeka'));
$this->headScript()->prependFile($this->assetUrl('vendor/jquery/jquery.min.js', 'Omeka'));
$this->trigger('view.layout');
$userBar = $this->userBar();
?>
<?php echo $this->doctype(); ?>
<?php echo $this->htmlElement('html'); ?>
    <head>
        <?php echo $this->headMeta(); ?>
        <?php echo $this->headTitle(); ?>
        <?php echo $this->headLink(); ?>
        <?php echo $this->headStyle(); ?>
        <?php echo $this->headScript(); ?>
        
        <style>
            <?php if ($accentColor = $this->themeSetting('accent_color')): ?>
            a:link,
            a:visited {
                color: <?php echo $accentColor; ?>
            }
            
            a:active,
            a:hover {
                color: <?php echo $accentColor; ?>;
                opacity: .75;
            }
            <?php endif; ?>
        </style>
    </head>
    <?php $content_class = $this->themeSetting('use_for_site_list') == 1 ? 'used-for-site-promo' : 'not-used-for-site-promo'; ?>
    <?php echo $this->htmlElement('body'); ?>
        <a id="skipnav" href="#content"><?php echo $this->translate('Skip to main content'); ?></a>
        <?php echo $userBar; ?>
        <div class="page-wrapper">
            <header class="<?php echo $content_class; ?>">
                <div>
                    <?php if ($this->getHelperPluginManager()->has('languageSwitcher')) echo $this->languageSwitcher(); ?>   
                    <div class="logo-title">
                        <a href="https://www.library.dartmouth.edu/">
                            <img src="<?php echo $this->assetUrl('img/Dartmouth_Libraries_Lockup_White_RGB.png') ?>" alt="Dartmouth Libraries" />
                        </a>
                        <div>
                            <h1>
                                <a href="<?php echo $site->url(); ?>" class="site-title">
                                    <span><?php echo $escape($siteTitle); ?></span>
                                </a>
                            </h1>
                            <?php if ($this->themeSetting('use_harmful_content') == 1 && $harmfulContent = $this->themeSetting('harmful_content')): ?>
                                <span class="harmful-content-wrapper">
                                    <span class="harmful-content-statement"><?php echo $harmfulContent; ?></span>
                            </span>
                            <?php endif; ?>
                        </div>
                    </div>
                        
                    <?php if ($this->themeSetting('use_for_site_list') != 1 || is_null($this->themeSetting('use_for_site_list'))): ?>
                        <a href="<?php echo explode("/admin", $site->adminUrl())[0] . '/'; ?>" class="all-exhibits-link">Exhibits Home</a>
                    <?php endif; ?>
                </div>

            </header>
            <div id="content" role="main" class="<?php echo $content_class; ?>">
                <?php echo $this->content; ?>
            </div>
            <footer role="contentinfo">
                <div class="standard-dcl-footer">
                    <div class="row-1">
                        <div class="region region-footer-first">
                            <nav role="navigation" aria-labelledby="block-footerlibrarylinks-menu" id="block-footerlibrarylinks" class="footer-library-list-links">
                                <h2 id="block-footerlibrarylinks-menu">
                                    Dartmouth Libraries 
                                </h2>
                                <ul class="menu menu--footer-library-links nav">
                                    <li class="expanded dropdown first"> <a href="https://www.library.dartmouth.edu/baker-berry" class="dropdown-toggle" data-toggle="dropdown" data-drupal-link-system-path="node/1799">Baker-Berry Library <span class="caret"></span></a> 
                                    <ul class="dropdown-menu">
                                        <li class="first"> <a href="https://www.library.dartmouth.edu/book-arts" data-drupal-link-system-path="node/1057">Book Arts Workshop</a> </li>
                                        <li> <a href="https://www.dartmouth.edu/library/maproom/">Evans Map Room</a> </li>
                                        <li class="last"> <a href="https://www.dartmouth.edu/library/mediactr/">Jones Media Center</a> </li>
                                    </ul>
                                    </li>
                                    <li> <a href="https://www.dartmouth.edu/library/biomed/">Health Sciences and Biomedical Libraries</a> </li>
                                    <li> <a href="https://www.library.dartmouth.edu/feldberg" data-drupal-link-system-path="node/1049">Feldberg Business & Engineering Library </a> </li>
                                    <li> <a href="https://www.library.dartmouth.edu/rauner" data-drupal-link-system-path="node/1809">Rauner Special Collections Library</a> </li>
                                    <li> <a href="https://www.library.dartmouth.edu/records-management" data-drupal-link-system-path="node/1149">Records Management</a> </li>
                                    <li class="last"> <a href="https://www.library.dartmouth.edu/sherman" data-drupal-link-system-path="node/1841">Sherman Art Library</a> </li>
                                </ul>
                            </nav>
                        </div>
                        <div class="region region-footer-second">
                            <nav role="navigation" aria-labelledby="block-footeraboutus-menu" id="block-footeraboutus">
                                <h2 id="block-footeraboutus-menu">
                                    About Us
                                </h2>
                                <div class="collapse" id="footer-aboutus-collapse" role="list" aria-expanded="false">
                                    <div role="listitem">
                                        <ul class="menu menu--footer-about-us nav">
                                            <li class="first"> <a href="https://www.library.dartmouth.edu/directory" data-drupal-link-system-path="directory">Staff Directory</a> </li>
                                            <li> <a href="https://www.library.dartmouth.edu/directory/subject-librarians">Subject Librarians</a> </li>
                                            <li> <a href="https://www.library.dartmouth.edu/about-us/dartmouth-libraries/departments" data-drupal-link-system-path="node/1824">Library Departments</a> </li>
                                            <li> <a href="https://www.library.dartmouth.edu/about-us/policies" data-drupal-link-system-path="node/1735">Policies</a> </li>
                                            <li> <a href="https://www.library.dartmouth.edu/about-us/employment" data-drupal-link-system-path="node/1740">Employment</a> </li>
                                            <li> <a href="https://www.library.dartmouth.edu/visit/accessibility" data-drupal-link-system-path="node/1713">Accessibility</a> </li>
                                            <li class="last"> <a href="https://researchguides.dartmouth.edu/government_documents/home">Federal Depository Library</a> </li>
                                        </ul>
                                    </div>
                                </div>
                            </nav>
                        </div>
                        <div class="region region-footer-third">
                            <section id="block-footercontactus" class="block block-block-content block-block-contentd216f7f4-bcca-429f-a900-db0ec9828214 clearfix">
                                <h2 class="block-title">
                                    Contact Us
                                </h2>
                                <div id="footer-contactus-collapse" role="list">
                                    <div role="listitem">
                                        <div class="field field--name-body field--type-text-with-summary field--label-hidden field--item">
                                            <ul class="library-info">
                                                <li>25 North Main Street<br> Hanover, NH, USA 03755</li>
                                                <li>Phone: <a href="tel:+1-603-646-2567">603-646-2567</a></li>
                                                <li><a href="https://www.library.dartmouth.edu/help/contact-us">Contact Us</a></li>
                                            </ul>
                                        </div>
                                    </div>
                                </div>
                            </section>
                            <section id="block-feedbacklinksimple" class="block block-block-content block-block-content342b733d-bd0a-4f71-bde8-f8185a93a7e9 clearfix">
                                <div class="field field--name-body field--type-text-with-summary field--label-hidden field--item">
                                    <p>
                                        <a href="https://www.library.dartmouth.edu/feedback">Give Us Feedback</a>
                                    </p>
                                </div>
                            </section>
                        </div>
                    </div>
                    <div class="row-2">
                        <div class="region region-footer-copyright">
                            <section id="block-bootstrap-dcl-sitebranding" class="display-footer block block-system block-system-branding-block clearfix">
                                <a class="logo" href="https://www.library.dartmouth.edu/" title="Dartmouth Libraries" rel="home"> <img src="<?php echo $this->assetUrl('img/Dartmouth_Libraries_Lockup_White_RGB.png') ?>" alt="Dartmouth Libraries" /> </a> 
                            </section>
                            <nav role="navigation" aria-labelledby="block-bootstrap-dcl-footercopyright-menu" id="block-bootstrap-dcl-footercopyright" class="display-footer">
                                <h2 class="visually-hidden" id="block-bootstrap-dcl-footercopyright-menu">
                                    Footer copyright 
                                </h2>
                                <ul class="menu menu--footer-copyright nav">
                                    <li class="first"> <a href="https://home.dartmouth.edu/">Dartmouth College</a> </li>
                                    <li> <a href="https://www.dartmouth.edu/copyright/">Copyright © <?php echo date("Y"); ?> Trustees of Dartmouth College</a> </li>
                                    <li> <a href="<?php echo implode('/', array_diff(explode("/", $site->adminUrl()),['site','s',$site->slug()])); ?>">Site Editor <?php echo $this->translate('Login') ;?></a></li>
                                </ul>
                            </nav>
                            <section id="block-footerconnectwithus" class="display-footer block block-block-content block-block-contentc36f95a7-e463-4baf-ab99-52cb3bdb2102 clearfix">
                                <div class="field field--name-body field--type-text-with-summary field--label-hidden field--item">
                                    <ul class="group footer-social" role="menu">
                                        <li role="menuitem"><a class="icon-facebook hide-txt" href="https://www.facebook.com/dartmouth.libraries"><span class="visually-hidden">Facebook</span></a></li>
                                        <li role="menuitem"><a class="icon-instagram hide-txt" href="https://www.instagram.com/dartmouthlibraries/"><span class="visually-hidden">Instagram</span></a></li>
                                        <li role="menuitem"><a class="icon-youtube hide-txt" href="https://www.youtube.com/playlist?list=PLA161361549CB448C"><span class="visually-hidden">YouTube</span></a></li>
                                    </ul>
                                    <div>
                                        <a href="https://www.library.dartmouth.edu/about/privacy-policy" data-entity-type="node" data-entity-uuid="a2b641d3-0a06-4065-be6f-92f1a6231a6b" data-entity-substitution="canonical" title="Privacy Policy">Privacy Policy</a>
                                    </div>
                                </div>
                            </section>
                            <section id="block-libchatwidget" class="block block-block-content block-block-contenta4e26191-1413-44e8-8319-abffcb732733 clearfix">
                                <div class="field field--name-body field--type-text-with-summary field--label-hidden field--item">
                                    <div id="libchat_5d029f1d85de468f625b7620d2788210">
                                    </div>
                                    <script type="text/javascript" src="//libanswers.dartmouth.edu/load_chat.php?hash=5d029f1d85de468f625b7620d2788210">
                                    </script>
                                </div>
                            </section>
                            <section id="block-dartmouthcollegeemergencybannerscriptblock" class="block block-dcl-dart-emergency-banner block-dcl-dart-emergency-banner-script-block clearfix">
                                <div id="dartmouth-emergency-banner-content-div" class="form-group">
                                </div>
                            </section>
                            <section id="block-emergencybannerscriptblock" class="block block-dcl-emergency-banner block-dcl-emergency-banner-script-block clearfix">
                                <div id="emergency-banner-content-div" class="form-group">
                                    <script src="//library.dartmouth.edu/emergency/banner.php">
            </script>
                                </div>
                            </section>
                        </div>
                    </div>
                </div>
            </footer>
                <a id="back-to-top-btn" href="#" data-offset="100" data-duration="300">
                    <svg aria-hidden="true" class="icon" viewBox="0 0 16 16"><title>Go to top of page</title><g stroke-width="1" stroke="currentColor"><polyline fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-miterlimit="10" points="15.5,11.5 8,4 0.5,11.5 "></polyline></g></svg>
                    <span class="sr-only">Back to top</span>
                </a>
        </div>
    </body>
</html>
